# Generated by Django 2.2.4 on 2019-09-12 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flow', '0003_auto_20190815_0420'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('abandon', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrawingNodeFlowRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('drawing_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.DrawingNode')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='flow.Flow')),
            ],
        ),
        migrations.AddField(
            model_name='drawingnode',
            name='flows',
            field=models.ManyToManyField(through='drawing.DrawingNodeFlowRel', to='flow.Flow'),
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('location', models.FileField(upload_to='drawing/%Y/%m/%d/')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('drawing_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.DrawingNode')),
            ],
        ),
    ]
