# Generated by Django 2.1 on 2019-11-19 07:00

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('location', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media', location='E://drawings'), upload_to='drawing/%Y/%m/%d/')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_dt', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrawingNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '检出'), (1, '检入'), (2, '完成'), (3, '废弃'), (4, '保留'), (5, '保留')], default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('abandon', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DrawingNodeFlowRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('drawing_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.DrawingNode')),
            ],
        ),
    ]
