# Generated by Django 2.2.4 on 2019-09-18 09:06

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='name',
        ),
        migrations.AddField(
            model_name='drawing',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drawing',
            name='deleted_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drawingnode',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '检出'), (1, '检入'), (2, '完成'), (3, '废弃'), (4, '保留'), (5, '保留')], default=0),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='location',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media', location='E://drawings'), upload_to='drawing/%Y/%m/%d/'),
        ),
    ]
