# Generated by Django 2.1 on 2019-11-19 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drawing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingnodeflowrel',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='flow.Flow'),
        ),
        migrations.AddField(
            model_name='drawingnode',
            name='flows',
            field=models.ManyToManyField(through='drawing.DrawingNodeFlowRel', to='flow.Flow'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drawing',
            name='drawing_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.DrawingNode'),
        ),
    ]
