# Generated by Django 2.2.4 on 2019-09-18 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_auto_20190815_0420'),
        ('drawing', '0002_auto_20190918_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawingNodeNodeRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='drawingnode',
            name='flows',
        ),
        migrations.DeleteModel(
            name='DrawingNodeFlowRel',
        ),
        migrations.AddField(
            model_name='drawingnodenoderel',
            name='drawing_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drawing.DrawingNode'),
        ),
        migrations.AddField(
            model_name='drawingnodenoderel',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='flow.Node'),
        ),
        migrations.AddField(
            model_name='drawingnode',
            name='nodes',
            field=models.ManyToManyField(through='drawing.DrawingNodeNodeRel', to='flow.Node'),
        ),
    ]
