# Generated by Django 2.2.1 on 2019-08-14 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='head_node',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sequence_flow', to='flow.Node'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未指派'), (1, '进行中'), (2, '已结束'), (3, '已冻结'), (4, '预留4')], default=0),
        ),
    ]
