# Generated by Django 2.2.1 on 2019-08-14 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_auto_20190815_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='next_node',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_node', to='flow.Node'),
        ),
    ]
